### ISSUE TITLE
`extract_osiris.py` fails due to LSLib

### ISSUE THREAD

**Issue by mycroftjr** [LaughingLeader/BG3ModdingTools#3]
With the latest stable LSLib (1.18.7) and a save file, extract_databases.py gives basically the same error shown in https://github.com/Norbyte/lslib/issues/209.
(When given story.div.osi instead of a save file, it doesn't error but also doesn't output anything.)

But with the pre-release version of LSLib that apparently fixes that (1.19.3), extract_databases.py gives what looks like an import error:
```
Traceback (most recent call last):
  File "D:\GitHub\BG3ModdingTools\scripts\extract_databases.py", line 94, in <module>
    from LSLib.LS import PackageReader, Package, AbstractFileInfo, LSFReader # type: ignore
ModuleNotFoundError: No module named 'LSLib'
```

Please advise?

Also, what exact version of python are you using? Because 3.10.11 is giving me huge problems when trying to install all the requirements.

**Comment by LaughingLeader** [comment]
The scripts looks for `LSLib.dll` in the path provided in the `-d` arg, such as this.
![dopus_2024-02-19_20-11-48](https://github.com/LaughingLeader/BG3ModdingTools/assets/2529658/87b04888-e3a1-4a54-9212-93d26a3b6ada)

Make sure you have the script requirements (run `InstallScriptRequirements.bat`, or manually install the packages in `scripts/requirements.txt`). Importing things from LSLib requires `pythonnet`, which is a package that lets you import C# assemblies into python.

The error you provided there suggests the assembly wasn't loaded for some reason.

Unrelated to this error, but lslib recently refactored a bunch of its code, so 1.18.7 will throw an error on AbstractFileInfo, since that class doesn't exist anymore. I've updated the script, and renamed it for clarity (use `extract_osiris.py` to build the text files of Databases.txt, Proc.txt etc).

I was able to run extract_osiris.py with lslib 1.18.7 and Python 3.11.5.
[Databases.txt](https://github.com/LaughingLeader/BG3ModdingTools/files/14338826/Databases.txt)

**Comment by mycroftjr** [comment]
With 1.18.7, I'm still getting this error, as shown in https://github.com/Norbyte/lslib/issues/209:
```
Traceback (most recent call last):
  File "D:\GitHub\BG3ModdingTools\scripts\extract_osiris.py", line 212, in <module>
    run(target_file, lslib_dll, output_dir)
  File "D:\GitHub\BG3ModdingTools\scripts\extract_osiris.py", line 164, in run
    package = package_reader.Read()
System.IO.InvalidDataException: File 'meta.lsf' has unsupported flags: 35
   at LSLib.LS.PackagedFileInfo.CreateFromEntry(FileEntry18 entry, Stream dataStream)
   at LSLib.LS.PackageReader.ReadFileListV18(BinaryReader reader, Package package)
   at LSLib.LS.PackageReader.ReadPackageV18(FileStream mainStream, BinaryReader reader)
   at LSLib.LS.PackageReader.Read()
```
It sounds like it might only happen with newer save files.

As for 1.19.3, it seems likely that the LSLib module was renamed? Since I'm able to get past line 65 using 1.18.7...
